mutation broadcast($request: BroadcastRequest!) {
    broadcast(request: $request) {
        __typename
        ... on RelayerResult {
            __typename
            txHash
            txId
        }
        ... on RelayError {
            __typename
            reason
        }
    }
}
