query ProxyActionStatus($proxyActionId: ProxyActionId!) {
    proxyActionStatus(proxyActionId: $proxyActionId) {
        ... on ProxyActionStatusResult {
            __typename
            txHash
            txId
            status
        }
        ... on ProxyActionError {
            __typename
            reason
            lastKnownTxId
        }
        ... on ProxyActionQueued {
            __typename
            queuedAt
        }
    }
}