query searchProfiles($request: SearchQueryRequest!) {
    search(request: $request) {
        ... on ProfileSearchResult {
            __typename
            items {
                handle
                name
                onChainIdentity {
                    ens {
                        name
                    }
                }
                ownedBy
            }
        }
    }
}
